---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Suhani Prajapati"
date: "September 11,2023"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r load-pkg-data}
#| message: false
library(magrittr)
# install the package 'Lahman'
#install.packages('Lahman')
# load the package
library(Lahman)
```

## Exercises

### Exercise 1

```{r glimpse-data}
dplyr::glimpse(Teams)
```

The `Teams` dataset has 3015 observations and 48 variables.

### Exercise 2

...

```{r}
mets <- Teams %>% 
  dplyr::filter(teamID == "NYN")
my_mets <- mets %>% 
  dplyr::filter(yearID %in% 2004:2012)
my_mets %>% 
  dplyr::select(yearID, teamID, W, L)
```

### Exercise 3

...

```{r}
mets_ben <- Teams |>
  dplyr::select(yearID, teamID, W, L, R, RA) |>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben
```

```{r}
mets_ben <- mets_ben |>
  dplyr::rename(RS = R)    # new name = old name
mets_ben
```

### Exercise 4

...

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(WPct = W / (W + L))
mets_ben
```

```{r}
mets_ben <- mets_ben %>% 
  dplyr::mutate(WPct_hat = 1 / (1 + (RA/RS)^2))
mets_ben
```

```{r}
mets_ben <- mets_ben %>% 
  dplyr::mutate(W_hat = WPct_hat * (W + L))
mets_ben
```

```{r}
dplyr::filter(mets_ben, W >= W_hat)
dplyr::filter(mets_ben, W < W_hat)
```

### Exercise 5

...

committing the code

### Exercise 6

...

```{r}
dplyr::arrange(mets_ben, desc(WPct))
```

### Exercise 7

...

```{r}
mets_ben %>% 
  dplyr::mutate(Diff = W - W_hat) |>
  dplyr::arrange(desc(Diff))
```

### Exercise 8

...

```{r}
mets_ben %>%
  dplyr::summarize(
    num_years = dplyr::n(), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct = sum(W) / sum(W+L), 
    sum_resid = sum(W - W_hat)
  )
```

### Exercise 9

...

```{r}
#no data available
```

### Exercise 10

...

```{r}
mets_ben <- mets_ben %>% 
  dplyr::mutate(
    gm = ifelse(
      yearID == 2004, 
      "Duquette", 
      ifelse(
        yearID >=  2011, 
        "Alderson", 
        "Minaya")
    )
  )
```

```{r}
mets_ben <- mets_ben %>% 
  dplyr::mutate(
    gm = dplyr::case_when(
      yearID == 2004 ~ "Duquette", 
      yearID >= 2011 ~ "Alderson", 
      TRUE ~ "Minaya"
    )
  )
```

```{r}
library(magrittr)
mets_ben %>% 
  dplyr::group_by(gm) %>% 
  dplyr::summarize(
    num_years = dplyr::n(), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct = sum(W) / sum(W + L), 
    sum_resid = sum(W - W_hat)
  ) %>%
  dplyr::arrange(desc(sum_resid))
```
